apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Chart.Name }}-backend-health
  namespace: {{ .Release.Namespace }}
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /api/health
        port: 5000
  targetRef:
    group: ""
    kind: Service
    name: {{ .Chart.Name }}-backend
