apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-backend
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: backend
  annotations:
    {{- toYaml .Values.service.backend.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-backend
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
      protocol: TCP
