apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-frontend
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: frontend
spec:
  # replicas managed by HPA
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-frontend
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/component: frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
